language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
before_script:
- npm install codeclimate-test-reporter -g
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- "./cc-test-reporter before-build"
script:
- npm test -- --coverage
after_script:
- "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
notifications:
  slack: andela:ODqDIMkl1Ds56Jxyrwc825vT
deploy:
  provider: heroku
  strategy: git
  api_key:
    secure: syccCt89fN0QWggAoWA38cfz81/DmDhzoozjzF1yqAnT6mhzL5oasE70Y6oiXDZBzyZ1+Qwx0j5V1+T0SI+ZoIAQFbsTnpG/NEQGnWwxk/G5UwA7PxIad1nA8DWz/FbA6YJhGF5/APJhBE7X02Hw1m/qad6WyaxebamVqQfsdsTWyVMsoxxIoC8BTZ5LAcogo3IbP3x++mkMrrz+JMiVDzDGeSs/TUNpbwLnEQ2Nhs51YRD4Ip0jp6cecb24//63TBIxxY7ZXZjDw4LzH9tmZfYkPVeg0l4G2tgiV75ldhbxjWVZqLK7XXt8CHUShr9QBXW9/OiJcaq7zsQ/WKHNlFcs7RDJ9LKCPhRaSHrFQPbYxnaEpQwmc5vAE2EouoAX6oU5I/MHCVVZr4xR8zzNrNjtOXdqju7gDSDVz+GyVdnJiF9dtNx5s7g/Gm4MOpgA6xBl7Q4XPKN793/GQYqQSKmGrwLpxhQLowZf8MlPVM1Ar2LebaolATakmqjrfNAM0kyrHY056+NLSkhL+OFJUN4IeTXKq8bPRtRQGGn7agc6mFKJ7c0SnOS8ccqBkxYmqAw+UCc+mLPP0x9sNWKkMczUQGmr/ZUuTTHcmoV7WMdxtGlpnLL7GbjdxklqTejSRTMdh72820tTmBZ4ZTOqLXTH3b9m96Hhyrny5DSG7IM=
  app:
    develop: authors-haven-frontend
    demo: authors-haven-dev
    ch-travis-deploy-160578604: authors-haven-frontend
