export const BEGIN_LOGIN = 'BEGIN_LOGIN';
export const FAIL_LOGIN = 'FAIL_LOGIN';
export const SUCCESS_LOGIN = 'SUCCESS_LOGIN';
export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';
