export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const TEST_REDUX = 'TEST_REDUX';
export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';
